export default function Termos(){
 return <main className="min-h-screen bg-[#050505] px-5 py-16 text-white sm:px-8"><div className="mx-auto max-w-3xl"><a href="/" className="font-black">JACOB<span className="text-[#F76303]">.</span></a><h1 className="mt-12 text-4xl font-black">Termos de Uso</h1><p className="mt-3 text-white/35">Última atualização: 29/09/2026</p><div className="mt-10 space-y-8 leading-7 text-white/60">
 <section><h2 className="text-xl font-bold text-white">1. Objetivo do site</h2><p className="mt-2">Este site apresenta serviços de desenvolvimento de sites e permite solicitar uma estimativa inicial e contato comercial.</p></section>
 <section><h2 className="text-xl font-bold text-white">2. Estimativas e propostas</h2><p className="mt-2">O preço público de entrada informado é a partir de R$497. A estimativa do simulador é inicial e não substitui uma proposta. O preço final depende do escopo aprovado.</p></section>
 <section><h2 className="text-xl font-bold text-white">3. Escopo e alterações</h2><p className="mt-2">O escopo, quantidade de páginas, funcionalidades e prazo são definidos antes do início. Estão incluídas até 2 rodadas de ajustes dentro do escopo contratado. O padrão de pagamento é 50% no início e 50% antes da publicação. Após a publicação, há 7 dias de suporte para correções relacionadas ao que foi entregue.</p></section>
 <section><h2 className="text-xl font-bold text-white">4. Domínio, hospedagem e terceiros</h2><p className="mt-2">Domínio, hospedagem e ferramentas externas não estão incluídos nos valores de entrada, salvo quando uma proposta específica indicar o contrário. Esses custos são pagos pelo cliente aos respectivos provedores.</p></section>
 <section><h2 className="text-xl font-bold text-white">5. Materiais do cliente</h2><p className="mt-2">O cliente deve fornecer materiais e informações que tenha autorização para utilizar. O checklist necessário será informado conforme o projeto.</p></section>
 <section><h2 className="text-xl font-bold text-white">6. Contato</h2><p className="mt-2">Contato comercial e atendimento: WhatsApp JACOB. (55 16 99244-5413).</p></section>
 </div></div></main>;
}