export default function Termos(){
 return <main className="min-h-screen bg-[#050505] px-5 py-16 text-white sm:px-8"><div className="mx-auto max-w-3xl"><a href="/" className="font-black">JACOB<span className="text-[#F76303]">.</span></a><h1 className="mt-12 text-4xl font-black">Termos de Uso</h1><p className="mt-3 text-white/35">Última atualização: 29/09/2026</p><div className="mt-10 space-y-8 leading-7 text-white/60">
 <section><h2 className="text-xl font-bold text-white">1. Objetivo do site</h2><p className="mt-2">Este site apresenta serviços de desenvolvimento de sites e permite solicitar uma estimativa inicial e contato comercial.</p></section>
 <section><h2 className="text-xl font-bold text-white">2. Estimativas e propostas</h2><p className="mt-2">O preço público de entrada informado é a partir de R$497. A estimativa do simulador é inicial e não substitui uma proposta. O preço final depende do escopo aprovado.</p></section>
 <section><h2 className="text-xl font-bold text-white">3. Escopo e alterações</h2><p className="mt-2">O escopo, quantidade de páginas, funcionalidades, alterações, prazos, suporte e condições de entrega devem constar da proposta: [PREENCHER regras comerciais].</p></section>
 <section><h2 className="text-xl font-bold text-white">4. Domínio, hospedagem e terceiros</h2><p className="mt-2">Custos de domínio, hospedagem e ferramentas externas dependem dos serviços escolhidos e das condições apresentadas na proposta: [PREENCHER].</p></section>
 <section><h2 className="text-xl font-bold text-white">5. Materiais do cliente</h2><p className="mt-2">O cliente deve fornecer materiais e informações que tenha autorização para utilizar. O checklist necessário será informado conforme o projeto.</p></section>
 <section><h2 className="text-xl font-bold text-white">6. Contato</h2><p className="mt-2">Contato comercial: [PREENCHER].</p></section>
 </div></div></main>;
}