export default function Privacidade(){
 return <main className="min-h-screen bg-[#050505] px-5 py-16 text-white sm:px-8"><div className="mx-auto max-w-3xl"><a href="/" className="font-black">JACOB<span className="text-[#F76303]">.</span></a><h1 className="mt-12 text-4xl font-black">Política de Privacidade</h1><p className="mt-3 text-white/35">Última atualização: 29/09/2026</p><div className="mt-10 space-y-8 leading-7 text-white/60">
 <section><h2 className="text-xl font-bold text-white">1. Quem somos</h2><p className="mt-2">A JACOB. Websites & Digital presta serviços de desenvolvimento de sites. Solicitações relacionadas à privacidade podem ser feitas pelo WhatsApp comercial: (55 16 99244-5413).</p></section>
 <section><h2 className="text-xl font-bold text-white">2. Dados coletados</h2><p className="mt-2">No simulador podemos coletar nome, WhatsApp, e-mail, tipo de negócio, tipo de site, situação atual, prazo, faixa de investimento, observações e dados de atribuição de campanha como UTM, fbclid e gclid.</p></section>
 <section><h2 className="text-xl font-bold text-white">3. Para que usamos os dados</h2><p className="mt-2">Usamos os dados para responder ao pedido de orçamento, entender o projeto, registrar leads, preparar propostas e medir o desempenho de campanhas, conforme as escolhas de consentimento aplicáveis.</p></section>
 <section><h2 className="text-xl font-bold text-white">4. Onde os dados podem ser processados</h2><p className="mt-2">O site utiliza Vercel para hospedagem da aplicação, Supabase para armazenamento dos leads e Google Analytics para métricas. Recursos de publicidade, como Meta Pixel ou Google Ads, só são ativados quando configurados e após o consentimento aplicável.</p></section>
 <section><h2 className="text-xl font-bold text-white">5. Retenção e direitos</h2><p className="mt-2">Os dados de leads são mantidos pelo tempo necessário para atendimento comercial, organização dos projetos e cumprimento de obrigações aplicáveis. Para solicitar acesso, correção ou exclusão dos dados, entre em contato pelo WhatsApp comercial informado nesta política.</p></section>
 <section><h2 className="text-xl font-bold text-white">6. Cookies e publicidade</h2><p className="mt-2">O site utiliza consentimento para controlar tecnologias de analytics e publicidade. O visitante pode aceitar ou recusar pelo banner disponível no site.</p></section>
 <section><h2 className="text-xl font-bold text-white">7. Contato</h2><p className="mt-2">Para assuntos relacionados a privacidade: WhatsApp comercial (55 16 99244-5413).</p></section>
 </div></div></main>;
}